org: leohangrai
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'

custom:
  tableName: 'todos-table-${self:provider.stage}'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
  memorySize: 128 #mb
  timeout: 10 #seconds
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource:
            - { "Fn::GetAtt": ["TodoTable", "Arn"] }
          Action:
            - 'dynamodb:Query'
            - 'dynamodb:Scan'
            - 'dynamodb:GetItem'
            - 'dynamodb:PutItem'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
  environment:
    TO_DO_TABLE: ${self:custom.tableName}

functions:
  default:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
  addTodo:
    handler: src/addTodo.handler
    events:
      - httpApi:
          path: /todo
          method: post

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
plugins:
  - serverless-offline
